'use strict';
/* ================= Laws library ================= */
const LAWCATS = [
  { id: 0, name: 'قوانين أساسية في الكهربائية (أوم وكيرشوف)' },
  ...CHAPTERS.map(c => ({ id: c.id, name: `الفصل ${c.id}: ${c.name}` }))
];
// ---- general electricity ----
LW({ id: 'ohm', cat: 0, name: 'قانون أوم', fx: '<i>V</i> = <i>I</i> <i>R</i>', sym: 'V فرق الجهد (V)، I التيار (A)، R المقاومة (Ω)', calc: { in: [['I', 'التيار I', 'A', 2], ['R', 'المقاومة R', 'Ω', 6]], out: 'فرق الجهد V', u: 'V', f: v => v.I * v.R } });
LW({ id: 'kcl', cat: 0, name: 'قانون كيرشوف الأول (قانون التيار — العقدة)', fx: 'Σ<i>I</i><sub>داخل</sub> = Σ<i>I</i><sub>خارج</sub> &nbsp;⟺&nbsp; Σ<i>I</i> = 0', sym: 'المجموع الجبري للتيارات عند أي نقطة تفرع يساوي صفراً؛ نتيجة لقانون حفظ الشحنة.', calc: { in: [['a', 'I₁ داخل', 'A', 3], ['b', 'I₂ خارج', 'A', 1.2]], out: 'I₃ الخارج', u: 'A', f: v => v.a - v.b } });
LW({ id: 'kvl', cat: 0, name: 'قانون كيرشوف الثاني (قانون الجهد — المسار المغلق)', fx: 'Σ<i>ε</i> = Σ<i>I R</i> &nbsp;⟺&nbsp; ΣΔ<i>V</i> = 0', sym: 'المجموع الجبري للقوى الدافعة الكهربائية في مسار مغلق = المجموع الجبري لهبوط الجهد فيه؛ نتيجة لقانون حفظ الطاقة.', calc: { in: [['e', 'ε المصدر', 'V', 12], ['r1', 'R₁', 'Ω', 2], ['r2', 'R₂', 'Ω', 4]], out: 'التيار في المسار', u: 'A', f: v => v.e / (v.r1 + v.r2) } });
LW({ id: 'rser', cat: 0, name: 'ربط المقاومات على التوالي', fx: '<i>R</i><sub>eq</sub> = <i>R</i><sub>1</sub> + <i>R</i><sub>2</sub> + <i>R</i><sub>3</sub> + …', sym: 'التيار نفسه في جميع المقاومات، والجهد الكلي = مجموع الجهود.', calc: { in: [['a', 'R₁', 'Ω', 10], ['b', 'R₂', 'Ω', 20], ['c', 'R₃', 'Ω', 30]], out: 'R المكافئة', u: 'Ω', f: v => v.a + v.b + v.c } });
LW({ id: 'rpar', cat: 0, name: 'ربط المقاومات على التوازي', fx: `${FR(1, '<i>R</i><sub>eq</sub>')} = ${FR(1, '<i>R</i><sub>1</sub>')} + ${FR(1, '<i>R</i><sub>2</sub>')} + …`, sym: 'فرق الجهد نفسه على جميع الفروع، والتيار الكلي = مجموع تيارات الفروع.', calc: { in: [['a', 'R₁', 'Ω', 10], ['b', 'R₂', 'Ω', 20], ['c', 'R₃ (0=لا يوجد)', 'Ω', 0]], out: 'R المكافئة', u: 'Ω', f: v => 1 / (1 / v.a + 1 / v.b + (v.c ? 1 / v.c : 0)) } });
LW({ id: 'power', cat: 0, name: 'القدرة الكهربائية', fx: '<i>P</i> = <i>I V</i> = <i>I</i>²<i>R</i> = ' + FR('<i>V</i>²', '<i>R</i>'), sym: 'P القدرة (W)', calc: { in: [['I', 'I', 'A', 2], ['R', 'R', 'Ω', 10]], out: 'القدرة P', u: 'W', f: v => v.I * v.I * v.R } });
LW({ id: 'emf', cat: 0, name: 'فرق جهد قطبي البطارية', fx: '<i>V</i> = <i>ε</i> − <i>I r</i>', sym: 'ε القوة الدافعة الكهربائية، r المقاومة الداخلية', calc: { in: [['e', 'ε', 'V', 12], ['I', 'I', 'A', 2], ['r', 'r', 'Ω', .5]], out: 'V', u: 'V', f: v => v.e - v.I * v.r } });
LW({ id: 'coul', cat: 0, name: 'الجهد الناتج عن شحنة نقطية', fx: `<i>V</i> = <i>k</i> ${FR('<i>Q</i>', '<i>r</i>')} , &nbsp; <i>k</i> = ${FR(1, '4π<i>ε</i><sub>0</sub>')} = 9×10⁹ N·m²/C²`, sym: 'ε₀ = 8.85×10⁻¹² C²/N·m² سماحية الفراغ' });
// ---- ch1 ----
LW({ id: 'capdef', cat: 1, name: 'سعة المتسعة', fx: `<i>C</i> = ${FR('<i>Q</i>', 'Δ<i>V</i>')}`, sym: 'C السعة (F = C/V)، Q الشحنة على أي من الصفيحتين، ΔV فرق الجهد بينهما. 1µF = 10⁻⁶F ، 1nF = 10⁻⁹F ، 1pF = 10⁻¹²F', calc: { in: [['Q', 'Q', 'µC', 120], ['V', 'ΔV', 'V', 12]], out: 'السعة C', u: 'µF', f: v => v.Q / v.V } });
LW({ id: 'cplate', cat: 1, name: 'سعة المتسعة ذات الصفيحتين المتوازيتين', fx: `<i>C</i> = ${FR('<i>ε</i><sub>0</sub> <i>A</i>', '<i>d</i>')} , &nbsp; <i>C</i><sub>k</sub> = ${FR('<i>k ε</i><sub>0</sub> <i>A</i>', '<i>d</i>')}`, sym: 'A المساحة المتقابلة (m²)، d البعد بين الصفيحتين (m)، k ثابت العزل', calc: { in: [['A', 'A', 'm²', .01], ['d', 'd', 'mm', .5], ['k', 'k', '', 1]], out: 'C', u: 'pF', f: v => v.k * 8.85e-12 * v.A / (v.d * 1e-3) * 1e12 } });
LW({ id: 'diel', cat: 1, name: 'تأثير العازل', fx: `<i>k</i> = ${FR('<i>C</i><sub>k</sub>', '<i>C</i>')} , &nbsp; Δ<i>V</i><sub>k</sub> = ${FR('Δ<i>V</i>', '<i>k</i>')} , &nbsp; <i>E</i><sub>k</sub> = ${FR('<i>E</i>', '<i>k</i>')}`, sym: 'عند إدخال عازل بين صفيحتي متسعة مشحونة ومفصولة تبقى الشحنة ثابتة ويقل الجهد والمجال بنسبة k', calc: { in: [['V', 'ΔV قبل العازل', 'V', 12], ['k', 'k', '', 6]], out: 'ΔVk بعد العازل', u: 'V', f: v => v.V / v.k } });
LW({ id: 'efield', cat: 1, name: 'المجال الكهربائي المنتظم بين الصفيحتين', fx: `<i>E</i> = ${FR('Δ<i>V</i>', '<i>d</i>')}`, sym: 'E (V/m)', calc: { in: [['V', 'ΔV', 'V', 100], ['d', 'd', 'mm', 2]], out: 'E', u: 'V/m', f: v => v.V / (v.d * 1e-3) } });
LW({ id: 'cpar', cat: 1, name: 'ربط المتسعات على التوازي', fx: '<i>C</i><sub>eq</sub> = <i>C</i><sub>1</sub> + <i>C</i><sub>2</sub> + <i>C</i><sub>3</sub> + …', sym: 'ΔV متساوٍ لجميع المتسعات ، Q<sub>total</sub> = Q₁ + Q₂ + … (السعة المكافئة أكبر من أكبر سعة)', calc: { in: [['a', 'C₁', 'µF', 4], ['b', 'C₂', 'µF', 8], ['c', 'C₃', 'µF', 12]], out: 'C المكافئة', u: 'µF', f: v => v.a + v.b + v.c } });
LW({ id: 'cser', cat: 1, name: 'ربط المتسعات على التوالي', fx: `${FR(1, '<i>C</i><sub>eq</sub>')} = ${FR(1, '<i>C</i><sub>1</sub>')} + ${FR(1, '<i>C</i><sub>2</sub>')} + … , &nbsp; <i>C</i><sub>eq</sub> = ${FR('<i>C</i><sub>1</sub><i>C</i><sub>2</sub>', '<i>C</i><sub>1</sub>+<i>C</i><sub>2</sub>')}`, sym: 'الشحنة متساوية على جميع المتسعات، ΔV<sub>total</sub> = ΔV₁ + ΔV₂ + … (السعة المكافئة أصغر من أصغر سعة)', calc: { in: [['a', 'C₁', 'µF', 6], ['b', 'C₂', 'µF', 9], ['c', 'C₃ (0=لا)', 'µF', 18]], out: 'C المكافئة', u: 'µF', f: v => 1 / (1 / v.a + 1 / v.b + (v.c ? 1 / v.c : 0)) } });
LW({ id: 'capE', cat: 1, name: 'الطاقة المختزنة في المجال الكهربائي للمتسعة', fx: `<i>PE</i> = ½ <i>Q</i> Δ<i>V</i> = ½ <i>C</i> (Δ<i>V</i>)² = ${FR('<i>Q</i>²', '2<i>C</i>')}`, sym: 'PE بالجول (J) — تمثل المساحة تحت منحني (Q–ΔV)', calc: { in: [['C', 'C', 'µF', 2], ['V', 'ΔV', 'V', 5000]], out: 'PE', u: 'J', f: v => .5 * v.C * 1e-6 * v.V * v.V } });
LW({ id: 'rcI', cat: 1, name: 'تيار الشحن/التفريغ الابتدائي وثابت الزمن', fx: `<i>I</i><sub>0</sub> = ${FR('Δ<i>V</i>', '<i>R</i>')} , &nbsp; <i>τ</i> = <i>R C</i> , &nbsp; <i>V</i><sub>C</sub>(<i>t</i>) = <i>V</i>(1 − <i>e</i><sup>−t/RC</sup>)`, sym: 'τ ثابت الزمن (s): الزمن اللازم لبلوغ 63% من الشحنة العظمى عند الشحن', calc: { in: [['R', 'R', 'kΩ', 10], ['C', 'C', 'µF', 100]], out: 'τ = RC', u: 's', f: v => v.R * 1e3 * v.C * 1e-6 } });
// ---- ch2 ----
LW({ id: 'lorentz', cat: 2, name: 'القوة المغناطيسية وقوة لورنز', fx: '<i>F</i><sub>B</sub> = <i>q v B</i> sin<i>θ</i> , &nbsp; <b>F</b> = <i>q</i><b>E</b> + <i>q</i>(<b>v</b>×<b>B</b>)', sym: 'B كثافة الفيض المغناطيسي (T)، θ الزاوية بين v و B', calc: { in: [['q', 'q', '×10⁻¹⁹C', 1.6], ['v', 'v', 'm/s', 1e6], ['B', 'B', 'T', .5], ['t', 'θ', '°', 90]], out: 'F', u: 'N', f: v => v.q * 1e-19 * v.v * v.B * Math.sin(v.t * Math.PI / 180) } });
LW({ id: 'flux', cat: 2, name: 'الفيض المغناطيسي', fx: '<i>Φ</i><sub>B</sub> = <i>B A</i> cos<i>θ</i>', sym: 'Φ بالويبر (Wb)، θ الزاوية بين متجه المساحة A و B', calc: { in: [['B', 'B', 'T', .5], ['A', 'A', 'm²', .01256], ['t', 'θ', '°', 0]], out: 'Φ', u: 'Wb', f: v => v.B * v.A * Math.cos(v.t * Math.PI / 180) } });
LW({ id: 'faraday', cat: 2, name: 'قانون فراداي في الحث الكهرومغناطيسي', fx: `<i>ε</i><sub>ind</sub> = −<i>N</i> ${FR('Δ<i>Φ</i><sub>B</sub>', 'Δ<i>t</i>')}`, sym: 'الإشارة السالبة تمثل قانون لنز: التيار المحتث يعاكس التغير المسبب له', calc: { in: [['N', 'N', 'لفة', 50], ['p', 'ΔΦ', 'Wb', -.0016], ['t', 'Δt', 's', .4]], out: 'ε', u: 'V', f: v => -v.N * v.p / v.t } });
LW({ id: 'lenz', cat: 2, name: 'قانون لنز', fx: '<i>I</i><sub>ind</sub> يولّد <b>B</b><sub>ind</sub> يعاكس ΔΦ<sub>B</sub>', sym: 'التيار المحتث في دائرة مغلقة يكون باتجاه بحيث يعاكس مجاله المغناطيسي التغير في الفيض المسبب له — تطبيق لحفظ الطاقة.' });
LW({ id: 'motional', cat: 2, name: 'القوة الدافعة الكهربائية الحركية', fx: `<i>ε</i><sub>motional</sub> = <i>v B ℓ</i> , &nbsp; <i>I</i> = ${FR('<i>v B ℓ</i>', '<i>R</i>')} , &nbsp; <i>P</i> = ${FR('<i>v</i>²<i>B</i>²<i>ℓ</i>²', '<i>R</i>')}`, sym: 'ℓ طول الساق (m)، v سرعتها (m/s)', calc: { in: [['v', 'v', 'm/s', 5], ['B', 'B', 'T', .8], ['l', 'ℓ', 'm', 1.6]], out: 'ε', u: 'V', f: v => v.v * v.B * v.l } });
LW({ id: 'gen', cat: 2, name: 'المولد الكهربائي للتيار المتناوب', fx: '<i>ε</i> = <i>N B A ω</i> sin(<i>ωt</i>) , &nbsp; <i>ε</i><sub>max</sub> = <i>N B A ω</i> , &nbsp; <i>ω</i> = 2π<i>f</i>', sym: 'ω السرعة الزاوية (rad/s)', calc: { in: [['N', 'N', '', 100], ['B', 'B', 'T', .2], ['A', 'A', 'm²', .05], ['f', 'f', 'Hz', 50]], out: 'εmax', u: 'V', f: v => v.N * v.B * v.A * 2 * Math.PI * v.f } });
LW({ id: 'backemf', cat: 2, name: 'تيار المحرك والقوة الدافعة المضادة', fx: `<i>I</i> = ${FR('<i>V</i><sub>applied</sub> − <i>ε</i><sub>back</sub>', '<i>R</i>')}`, sym: 'تزداد ε<sub>back</sub> بزيادة سرعة دوران المحرك فيقل التيار', calc: { in: [['V', 'V المسلطة', 'V', 120], ['e', 'εback', 'V', 100], ['R', 'R', 'Ω', 5]], out: 'I', u: 'A', f: v => (v.V - v.e) / v.R } });
LW({ id: 'self', cat: 2, name: 'الحث الذاتي', fx: `<i>ε</i><sub>ind</sub> = −<i>L</i> ${FR('Δ<i>I</i>', 'Δ<i>t</i>')} , &nbsp; <i>N Φ</i><sub>B</sub> = <i>L I</i>`, sym: 'L معامل الحث الذاتي بالهنري (H = V·s/A)', calc: { in: [['L', 'L', 'mH', 2.5], ['I', 'ΔI', 'A', -8], ['t', 'Δt', 's', .25]], out: 'ε', u: 'V', f: v => -v.L * 1e-3 * v.I / v.t } });
LW({ id: 'indE', cat: 2, name: 'الطاقة المختزنة في المجال المغناطيسي للمحث', fx: '<i>PE</i> = ½ <i>L I</i>²', calc: { in: [['L', 'L', 'mH', 2.5], ['I', 'I', 'A', 4]], out: 'PE', u: 'J', f: v => .5 * v.L * 1e-3 * v.I * v.I } });
LW({ id: 'mutual', cat: 2, name: 'الحث المتبادل', fx: `<i>ε</i><sub>ind(2)</sub> = −<i>M</i> ${FR('Δ<i>I</i><sub>1</sub>', 'Δ<i>t</i>')} , &nbsp; <i>M</i> = <i>k</i>√(<i>L</i><sub>1</sub><i>L</i><sub>2</sub>)`, sym: 'M معامل الحث المتبادل (H)، k معامل الاقتران (1 للاقتران التام)', calc: { in: [['a', 'L₁', 'H', .5], ['b', 'L₂', 'H', .08], ['k', 'k', '', 1]], out: 'M', u: 'H', f: v => v.k * Math.sqrt(v.a * v.b) } });
// ---- ch3 ----
LW({ id: 'acv', cat: 3, name: 'الفولطية والتيار الآنيان', fx: '<i>V</i> = <i>V</i><sub>m</sub> sin(<i>ωt</i>) , &nbsp; <i>I</i> = <i>I</i><sub>m</sub> sin(<i>ωt</i> + <i>Φ</i>)', sym: 'Φ زاوية فرق الطور بين التيار والفولطية' });
LW({ id: 'rms', cat: 3, name: 'المقدار المؤثر (جذر معدل المربع)', fx: `<i>I</i><sub>eff</sub> = ${FR('<i>I</i><sub>m</sub>', '√2')} = 0.707 <i>I</i><sub>m</sub> , &nbsp; <i>V</i><sub>eff</sub> = 0.707 <i>V</i><sub>m</sub>`, sym: 'المقدار المؤثر للتيار المتناوب يساوي مقدار التيار المستمر الذي يولد التأثير الحراري نفسه في المقاومة نفسها وللفترة الزمنية نفسها', calc: { in: [['m', 'القيمة العظمى', '', 424.2]], out: 'المقدار المؤثر', u: '', f: v => v.m / Math.SQRT2 } });
LW({ id: 'pavgR', cat: 3, name: 'القدرة المتوسطة في مقاومة صرف', fx: `<i>P</i><sub>av</sub> = ${FR('<i>I</i><sub>m</sub><i>V</i><sub>m</sub>', '2')} = <i>I</i><sub>eff</sub>² <i>R</i> = <i>I</i><sub>eff</sub> <i>V</i><sub>eff</sub>`, calc: { in: [['I', 'Ieff', 'A', 3], ['R', 'R', 'Ω', 100]], out: 'Pav', u: 'W', f: v => v.I * v.I * v.R } });
LW({ id: 'xl', cat: 3, name: 'رادة الحث', fx: '<i>X</i><sub>L</sub> = <i>ωL</i> = 2π<i>f L</i>', sym: 'X<sub>L</sub> تتناسب طردياً مع f و L. التيار يتأخر عن الفولطية بـ 90°', calc: { in: [['f', 'f', 'Hz', 10], ['L', 'L', 'H', .0159]], out: 'XL', u: 'Ω', f: v => 2 * Math.PI * v.f * v.L } });
LW({ id: 'xc', cat: 3, name: 'رادة السعة', fx: `<i>X</i><sub>C</sub> = ${FR(1, '<i>ωC</i>')} = ${FR(1, '2π<i>f C</i>')}`, sym: 'X<sub>C</sub> تتناسب عكسياً مع f و C. التيار يتقدم على الفولطية بـ 90°', calc: { in: [['f', 'f', 'Hz', 5], ['C', 'C', 'µF', 1.273]], out: 'XC', u: 'Ω', f: v => 1 / (2 * Math.PI * v.f * v.C * 1e-6) } });
LW({ id: 'imped', cat: 3, name: 'الممانعة في دائرة RLC متوالية', fx: '<i>Z</i> = √(<i>R</i>² + (<i>X</i><sub>L</sub> − <i>X</i><sub>C</sub>)²) , &nbsp; <i>V</i><sub>T</sub>² = <i>V</i><sub>R</sub>² + (<i>V</i><sub>L</sub> − <i>V</i><sub>C</sub>)²', calc: { in: [['R', 'R', 'Ω', 40], ['L', 'XL', 'Ω', 120], ['C', 'XC', 'Ω', 90]], out: 'Z', u: 'Ω', f: v => Math.hypot(v.R, v.L - v.C) } });
LW({ id: 'phase', cat: 3, name: 'زاوية فرق الطور', fx: `tan<i>Φ</i> = ${FR('<i>X</i><sub>L</sub> − <i>X</i><sub>C</sub>', '<i>R</i>')} = ${FR('<i>V</i><sub>L</sub> − <i>V</i><sub>C</sub>', '<i>V</i><sub>R</sub>')}`, sym: 'Φ موجبة: خواص حثية، سالبة: خواص سعوية، صفر: خواص أومية (رنين)', calc: { in: [['R', 'R', 'Ω', 40], ['L', 'XL', 'Ω', 120], ['C', 'XC', 'Ω', 90]], out: 'Φ', u: '°', f: v => Math.atan((v.L - v.C) / v.R) * 180 / Math.PI } });
LW({ id: 'pf', cat: 3, name: 'عامل القدرة والقدرة الحقيقية والظاهرية', fx: `<i>pf</i> = cos<i>Φ</i> = ${FR('<i>P</i><sub>real</sub>', '<i>P</i><sub>app</sub>')} , &nbsp; <i>P</i><sub>real</sub> = <i>I V</i><sub>T</sub> cos<i>Φ</i> , &nbsp; <i>P</i><sub>app</sub> = <i>I V</i><sub>T</sub>`, sym: 'القدرة الحقيقية بالواط (W)، والظاهرية بالفولط·أمبير (VA)', calc: { in: [['I', 'I', 'A', 4], ['V', 'VT', 'V', 200], ['p', 'Φ', '°', 37]], out: 'Preal', u: 'W', f: v => v.I * v.V * Math.cos(v.p * Math.PI / 180) } });
LW({ id: 'reson', cat: 3, name: 'التردد الرنيني', fx: `<i>f</i><sub>r</sub> = ${FR(1, '2π√(<i>LC</i>)')} , &nbsp; <i>ω</i><sub>r</sub> = ${FR(1, '√(<i>LC</i>)')} , &nbsp; <i>X</i><sub>L</sub> = <i>X</i><sub>C</sub> ⟹ <i>Z</i> = <i>R</i>`, sym: 'عند الرنين يكون التيار أعظم ما يمكن وعامل القدرة = 1', calc: { in: [['L', 'L', 'H', 2], ['C', 'C', 'µF', .5]], out: 'fr', u: 'Hz', f: v => 1 / (2 * Math.PI * Math.sqrt(v.L * v.C * 1e-6)) } });
LW({ id: 'qf', cat: 3, name: 'عامل النوعية', fx: `<i>Q</i><sub>f</sub> = ${FR('<i>ω</i><sub>r</sub>', 'Δ<i>ω</i>')} = ${FR(1, '<i>R</i>')}√(${FR('<i>L</i>', '<i>C</i>')}) , &nbsp; Δ<i>ω</i> = ${FR('<i>R</i>', '<i>L</i>')}`, sym: 'كلما صغرت المقاومة ضاق نطاق التردد وزادت حدة منحني الرنين', calc: { in: [['R', 'R', 'Ω', 500], ['L', 'L', 'H', 2], ['C', 'C', 'µF', .5]], out: 'Qf', u: '', f: v => Math.sqrt(v.L / (v.C * 1e-6)) / v.R } });
LW({ id: 'rlcpar', cat: 3, name: 'دائرة RLC متوازية', fx: '<i>I</i><sub>T</sub> = √(<i>I</i><sub>R</sub>² + (<i>I</i><sub>C</sub> − <i>I</i><sub>L</sub>)²) , &nbsp; tan<i>Φ</i> = ' + FR('<i>I</i><sub>C</sub> − <i>I</i><sub>L</sub>', '<i>I</i><sub>R</sub>'), sym: 'الفولطية مشتركة على الأفرع', calc: { in: [['a', 'IR', 'A', 3], ['b', 'IC', 'A', 8], ['c', 'IL', 'A', 12]], out: 'IT', u: 'A', f: v => Math.hypot(v.a, v.b - v.c) } });
// ---- ch4 ----
LW({ id: 'wave', cat: 4, name: 'العلاقة بين السرعة والتردد والطول الموجي', fx: '<i>c</i> = <i>f λ</i>', sym: 'c = 3×10⁸ m/s في الفراغ', calc: { in: [['f', 'f', 'MHz', 100]], out: 'λ', u: 'm', f: v => 3e8 / (v.f * 1e6) } });
LW({ id: 'cmax', cat: 4, name: 'سرعة الموجات الكهرومغناطيسية (ماكسويل)', fx: `<i>c</i> = ${FR(1, '√(<i>μ</i><sub>0</sub><i>ε</i><sub>0</sub>)')} , &nbsp; <i>v</i> = ${FR(1, '√(<i>με</i>)')}`, sym: 'μ₀ = 4π×10⁻⁷ H/m ، ε₀ = 8.854×10⁻¹² F/m' });
LW({ id: 'disp', cat: 4, name: 'تيار الإزاحة', fx: `<i>I</i><sub>d</sub> ∝ ${FR('Δ<i>E</i>', 'Δ<i>t</i>')}`, sym: 'المجال الكهربائي المتغير يولد مجالاً مغناطيسياً (فرضية ماكسويل)' });
LW({ id: 'ant', cat: 4, name: 'طول الهوائي', fx: `<i>ℓ</i> = ${FR('<i>λ</i>', '2')} (ثنائي القطب) , &nbsp; <i>ℓ</i> = ${FR('<i>λ</i>', '4')} (هوائي مؤرّض)`, calc: { in: [['f', 'f', 'MHz', 200]], out: 'ℓ = λ/2', u: 'm', f: v => 3e8 / (v.f * 1e6) / 2 } });
// ---- ch5 ----
LW({ id: 'phdiff', cat: 5, name: 'فرق الطور وفرق المسار البصري', fx: `<i>Φ</i> = ${FR('2π', '<i>λ</i>')} Δ<i>ℓ</i>`, calc: { in: [['l', 'Δℓ', 'λ', 1.5]], out: 'Φ', u: 'rad', f: v => 2 * Math.PI * v.l } });
LW({ id: 'constr', cat: 5, name: 'شرطا التداخل البنّاء والإتلافي', fx: 'بنّاء: Δ<i>ℓ</i> = <i>mλ</i> &nbsp;&nbsp; إتلافي: Δ<i>ℓ</i> = (<i>m</i> + ½)<i>λ</i>', sym: 'm = 0, 1, 2, 3, …' });
LW({ id: 'young', cat: 5, name: 'تجربة شقي يونك', fx: `<i>d</i> sin<i>θ</i> = <i>mλ</i> , &nbsp; <i>y</i><sub>m</sub> = ${FR('<i>λ L</i>', '<i>d</i>')}<i>m</i> , &nbsp; Δ<i>y</i> = ${FR('<i>λ L</i>', '<i>d</i>')}`, sym: 'd البعد بين الشقين، L بعد الشاشة، Δy فاصلة الهدب', calc: { in: [['l', 'λ', 'nm', 633], ['L', 'L', 'm', 1], ['d', 'd', 'mm', .2]], out: 'Δy', u: 'mm', f: v => v.l * 1e-9 * v.L / (v.d * 1e-3) * 1e3 } });
LW({ id: 'thin', cat: 5, name: 'التداخل في الأغشية الرقيقة (انعكاس)', fx: `2<i>n t</i> + ${FR('<i>λ</i>', '2')} = <i>mλ</i> (مضيء) , &nbsp; <i>λ</i><sub>n</sub> = ${FR('<i>λ</i>', '<i>n</i>')}`, sym: 'انقلاب طور 180° عند الانعكاس من الوسط الأكبر معامل انكسار' });
LW({ id: 'slit', cat: 5, name: 'الحيود من شق مفرد', fx: '<i>ℓ</i> sin<i>θ</i> = <i>mλ</i> (هدب مظلم) , &nbsp; <i>m</i> = ±1, ±2, …', sym: 'ℓ عرض الشق', calc: { in: [['a', 'عرض الشق', 'µm', 5], ['l', 'λ', 'nm', 600]], out: 'θ₁', u: '°', f: v => Math.asin(Math.min(1, v.l * 1e-9 / (v.a * 1e-6))) * 180 / Math.PI } });
LW({ id: 'grating', cat: 5, name: 'محزز الحيود', fx: `<i>d</i> sin<i>θ</i> = <i>mλ</i> , &nbsp; <i>d</i> = ${FR('<i>W</i>', '<i>N</i>')}`, calc: { in: [['N', 'خطوط/cm', '', 6000], ['l', 'λ', 'nm', 632.8], ['m', 'm', '', 1]], out: 'θ', u: '°', f: v => Math.asin(Math.min(1, v.m * v.l * 1e-9 / (0.01 / v.N))) * 180 / Math.PI } });
LW({ id: 'malus', cat: 5, name: 'قانون مالوس', fx: '<i>I</i> = <i>I</i><sub>0</sub> cos²<i>θ</i>', sym: 'θ الزاوية بين محوري المستقطب والمحلل', calc: { in: [['I', 'I₀', '%', 100], ['t', 'θ', '°', 60]], out: 'I', u: '%', f: v => v.I * Math.cos(v.t * Math.PI / 180) ** 2 } });
LW({ id: 'brew', cat: 5, name: 'قانون بروستر', fx: 'tan<i>θ</i><sub>p</sub> = <i>n</i>', sym: 'عند زاوية بروستر يكون الشعاع المنعكس مستقطباً كلياً ومتعامداً مع المنكسر', calc: { in: [['n', 'n', '', 1.33]], out: 'θp', u: '°', f: v => Math.atan(v.n) * 180 / Math.PI } });
LW({ id: 'rayl', cat: 5, name: 'استطارة رايلي', fx: `<i>I</i><sub>scatter</sub> ∝ ${FR(1, '<i>λ</i><sup>4</sup>')}`, calc: { in: [['a', 'λ₁ (أزرق)', 'nm', 400], ['b', 'λ₂ (أحمر)', 'nm', 700]], out: 'نسبة الاستطارة', u: '×', f: v => (v.b / v.a) ** 4 } });
// ---- ch6 ----
LW({ id: 'stefan', cat: 6, name: 'قانون ستيفان – بولتزمان', fx: '<i>I</i> = <i>σ T</i>⁴', sym: 'σ = 5.67×10⁻⁸ W/m²K⁴', calc: { in: [['T', 'T', 'K', 5800]], out: 'I', u: 'W/m²', f: v => 5.67e-8 * v.T ** 4 } });
LW({ id: 'wien', cat: 6, name: 'قانون الإزاحة لفين', fx: '<i>λ</i><sub>m</sub> <i>T</i> = 2.898×10⁻³ m·K', calc: { in: [['T', 'T', 'K', 308]], out: 'λm', u: 'µm', f: v => 2.898e-3 / v.T * 1e6 } });
LW({ id: 'planck', cat: 6, name: 'طاقة الفوتون (بلانك)', fx: `<i>E</i> = <i>h f</i> = ${FR('<i>h c</i>', '<i>λ</i>')}`, sym: 'h = 6.63×10⁻³⁴ J·s ، 1 eV = 1.6×10⁻¹⁹ J', calc: { in: [['l', 'λ', 'nm', 500]], out: 'E', u: 'eV', f: v => 6.63e-34 * 3e8 / (v.l * 1e-9) / 1.6e-19 } });
LW({ id: 'photo', cat: 6, name: 'معادلة أينشتاين الكهروضوئية', fx: '(<i>KE</i>)<sub>max</sub> = <i>h f</i> − <i>W</i> = <i>e V</i><sub>s</sub> , &nbsp; <i>W</i> = <i>h f</i><sub>0</sub> , &nbsp; <i>λ</i><sub>0</sub> = ' + FR('<i>hc</i>', '<i>W</i>'), sym: 'W دالة الشغل، f₀ تردد العتبة، Vs جهد القطع (الإيقاف)', calc: { in: [['l', 'λ', 'nm', 300], ['W', 'W', 'eV', 2.46]], out: 'KEmax', u: 'eV', f: v => 6.63e-34 * 3e8 / (v.l * 1e-9) / 1.6e-19 - v.W } });
LW({ id: 'debroglie', cat: 6, name: 'طول موجة دي برولي', fx: `<i>λ</i> = ${FR('<i>h</i>', '<i>p</i>')} = ${FR('<i>h</i>', '<i>m v</i>')}`, calc: { in: [['v', 'v الإلكترون', 'm/s', 6e6]], out: 'λ', u: 'nm', f: v => 6.63e-34 / (9.11e-31 * v.v) * 1e9 } });
LW({ id: 'heis', cat: 6, name: 'مبدأ اللادقة لهايزنبرك', fx: `Δ<i>x</i> Δ<i>p</i> ≥ ${FR('<i>h</i>', '4π')} , &nbsp; Δ<i>E</i> Δ<i>t</i> ≥ ${FR('<i>h</i>', '4π')}` });
LW({ id: 'gamma', cat: 6, name: 'عامل لورنز وتمدد الزمن وتقلص الطول', fx: `<i>γ</i> = ${FR(1, '√(1 − <i>v</i>²/<i>c</i>²)')} , &nbsp; <i>t</i> = <i>γ t</i><sub>0</sub> , &nbsp; <i>L</i> = ${FR('<i>L</i><sub>0</sub>', '<i>γ</i>')} , &nbsp; <i>m</i> = <i>γ m</i><sub>0</sub>`, calc: { in: [['v', 'v/c', '', .8]], out: 'γ', u: '', f: v => 1 / Math.sqrt(1 - v.v * v.v) } });
LW({ id: 'emc2', cat: 6, name: 'تكافؤ الكتلة والطاقة', fx: '<i>E</i> = <i>m c</i>²', calc: { in: [['m', 'm', 'g', 1]], out: 'E', u: 'J', f: v => v.m * 1e-3 * 9e16 } });
// ---- ch7 ----
LW({ id: 'gap', cat: 7, name: 'فجوة الطاقة المحظورة', fx: '<i>E</i><sub>g</sub>(Si) ≈ 1.1 eV , &nbsp; <i>E</i><sub>g</sub>(Ge) ≈ 0.72 eV (عند 300K)', sym: 'العوازل: فجوة كبيرة (≈ 5eV أو أكثر)، الموصلات: تداخل الحزم' });
LW({ id: 'barrier', cat: 7, name: 'حاجز الجهد في الثنائي pn', fx: '<i>V</i><sub>barrier</sub>(Si) ≈ 0.7 V , &nbsp; (Ge) ≈ 0.3 V', sym: 'يعتمد على نوع البلورة ونسبة الشوائب ودرجة الحرارة' });
LW({ id: 'diodeEq', cat: 7, name: 'معادلة تيار الثنائي (شوكلي)', fx: '<i>I</i> = <i>I</i><sub>s</sub>(<i>e</i><sup><i>V</i>/<i>nV</i><sub>T</sub></sup> − 1) , &nbsp; <i>V</i><sub>T</sub> = <i>kT</i>/<i>e</i> ≈ 25.9 mV', sym: 'للإطلاع — تصف منحني الخواص (I–V) للثنائي' });
LW({ id: 'trI', cat: 7, name: 'تيارات الترانزستور', fx: '<i>I</i><sub>E</sub> = <i>I</i><sub>C</sub> + <i>I</i><sub>B</sub>', calc: { in: [['E', 'IE', 'mA', 3], ['C', 'IC', 'mA', 2.94]], out: 'IB', u: 'mA', f: v => v.E - v.C } });
LW({ id: 'gainCB', cat: 7, name: 'ربح التيار (القاعدة المشتركة)', fx: `<i>α</i> = ${FR('<i>I</i><sub>C</sub>', '<i>I</i><sub>E</sub>')}`, calc: { in: [['C', 'IC', 'mA', 2.94], ['E', 'IE', 'mA', 3]], out: 'α', u: '', f: v => v.C / v.E } });
LW({ id: 'gainCE', cat: 7, name: 'ربح التيار (الباعث المشترك)', fx: `<i>β</i> = ${FR('<i>I</i><sub>C</sub>', '<i>I</i><sub>B</sub>')}`, calc: { in: [['C', 'IC', 'mA', 3.65], ['B', 'IB', 'µA', 50]], out: 'β', u: '', f: v => v.C * 1e3 / v.B } });
LW({ id: 'gainV', cat: 7, name: 'ربح الفولطية وربح القدرة', fx: `<i>A</i><sub>v</sub> = ${FR('<i>V</i><sub>out</sub>', '<i>V</i><sub>in</sub>')} , &nbsp; <i>G</i> = ${FR('<i>P</i><sub>out</sub>', '<i>P</i><sub>in</sub>')} = <i>α</i> × <i>A</i><sub>v</sub>`, calc: { in: [['a', 'α', '', .98], ['A', 'Av', '', 784]], out: 'G', u: '', f: v => v.a * v.A } });
// ---- ch8 ----
LW({ id: 'bohrE', cat: 8, name: 'طاقة المستوى في ذرة الهيدروجين (بور)', fx: `<i>E</i><sub>n</sub> = −${FR('13.6', '<i>n</i>²')} eV , &nbsp; <i>L</i><sub>n</sub> = <i>n</i>${FR('<i>h</i>', '2π')}`, calc: { in: [['n', 'n', '', 2]], out: 'En', u: 'eV', f: v => -13.6 / (v.n * v.n) } });
LW({ id: 'trans', cat: 8, name: 'تردد الفوتون المنبعث عند الانتقال', fx: `<i>h f</i> = <i>E</i><sub>f</sub> − <i>E</i><sub>i</sub> , &nbsp; ${FR(1, '<i>λ</i>')} = <i>R</i><sub>H</sub>(${FR(1, '<i>n</i><sub>f</sub>²')} − ${FR(1, '<i>n</i><sub>i</sub>²')})`, sym: 'لايمان n=1، بالمر n=2، باشن n=3، براكت n=4، فوند n=5', calc: { in: [['i', 'ni', '', 3], ['f', 'nf', '', 2]], out: 'λ', u: 'nm', f: v => 1e9 / (1.097e7 * (1 / (v.f * v.f) - 1 / (v.i * v.i))) } });
LW({ id: 'xmin', cat: 8, name: 'أقصر طول موجي للأشعة السينية', fx: `(<i>KE</i>)<sub>max</sub> = <i>eV</i> = <i>h f</i><sub>max</sub> , &nbsp; <i>λ</i><sub>min</sub> = ${FR('<i>h c</i>', '<i>e V</i>')}`, calc: { in: [['V', 'V', 'kV', 12.4]], out: 'λmin', u: 'nm', f: v => 6.63e-34 * 3e8 / (1.6e-19 * v.V * 1e3) * 1e9 } });
LW({ id: 'compton', cat: 8, name: 'تأثير كومبتون', fx: `<i>λ</i>′ − <i>λ</i> = ${FR('<i>h</i>', '<i>m</i><sub>e</sub><i>c</i>')}(1 − cos<i>θ</i>)`, sym: 'h/m<sub>e</sub>c = 0.00243 nm طول موجة كومبتون', calc: { in: [['t', 'θ', '°', 60]], out: 'Δλ', u: 'nm', f: v => 2.426e-3 * (1 - Math.cos(v.t * Math.PI / 180)) } });
LW({ id: 'boltz', cat: 8, name: 'توزيع بولتزمان', fx: `${FR('<i>N</i><sub>2</sub>', '<i>N</i><sub>1</sub>')} = exp[${FR('−(<i>E</i><sub>2</sub> − <i>E</i><sub>1</sub>)', '<i>kT</i>')}]`, sym: 'في الاتزان الحراري N₂ < N₁ دائماً؛ الليزر يتطلب توزيعاً معكوساً N₂ > N₁', calc: { in: [['E', 'ΔE', 'eV', 1.8], ['T', 'T', 'K', 300]], out: 'N₂/N₁', u: '', f: v => Math.exp(-v.E * 1.6e-19 / (1.38e-23 * v.T)) } });
// ---- ch9 ----
LW({ id: 'nuc', cat: 9, name: 'العدد الكتلي وشحنة النواة', fx: '<i>A</i> = <i>Z</i> + <i>N</i> , &nbsp; <i>q</i> = <i>Z e</i>', calc: { in: [['Z', 'Z', '', 79]], out: 'q', u: 'C', f: v => v.Z * 1.6e-19 } });
LW({ id: 'radius', cat: 9, name: 'نصف قطر النواة', fx: '<i>R</i> = <i>r</i><sub>0</sub> <i>A</i><sup>1/3</sup> , &nbsp; <i>r</i><sub>0</sub> = 1.2 F', calc: { in: [['A', 'A', '', 64]], out: 'R', u: 'F (fm)', f: v => 1.2 * Math.cbrt(v.A) } });
LW({ id: 'bind', cat: 9, name: 'طاقة الربط النووية', fx: '<i>E</i><sub>b</sub> = Δ<i>m c</i>² = (<i>Z M</i><sub>H</sub> + <i>N m</i><sub>n</sub> − <i>M</i>) × 931 MeV/u , &nbsp; <i>E</i>′<sub>b</sub> = ' + FR('<i>E</i><sub>b</sub>', '<i>A</i>'), sym: 'M<sub>H</sub> = 1.007825u ، m<sub>n</sub> = 1.008665u', calc: { in: [['Z', 'Z', '', 7], ['N', 'N', '', 7], ['M', 'M', 'u', 14.003074]], out: 'Eb', u: 'MeV', f: v => (v.Z * 1.007825 + v.N * 1.008665 - v.M) * 931 } });
LW({ id: 'qval', cat: 9, name: 'طاقة التفاعل / الانحلال النووي', fx: '<i>Q</i> = [(<i>M</i><sub>a</sub> + <i>M</i><sub>X</sub>) − (<i>M</i><sub>Y</sub> + <i>M</i><sub>b</sub>)] × 931 MeV , &nbsp; <i>Q</i><sub>α</sub> = [<i>M</i><sub>P</sub> − <i>M</i><sub>D</sub> − <i>M</i><sub>α</sub>] × 931', sym: 'Q > 0 تفاعل باعث للطاقة، Q < 0 ماص للطاقة', calc: { in: [['p', 'Mp', 'u', 226.025406], ['d', 'Md', 'u', 222.017574], ['a', 'Mα', 'u', 4.002603]], out: 'Qα', u: 'MeV', f: v => (v.p - v.d - v.a) * 931 } });
LW({ id: 'decay', cat: 9, name: 'قانون الانحلال الإشعاعي وعمر النصف', fx: `<i>N</i> = <i>N</i><sub>0</sub> (½)<sup><i>t</i>/<i>T</i><sub>½</sub></sup> = <i>N</i><sub>0</sub> <i>e</i><sup>−<i>λt</i></sup> , &nbsp; <i>T</i><sub>½</sub> = ${FR('0.693', '<i>λ</i>')}`, sym: 'للإطلاع والتوسع', calc: { in: [['N', 'N₀', '', 1000], ['t', 't', 's', 20], ['T', 'T½', 's', 10]], out: 'N', u: '', f: v => v.N * Math.pow(.5, v.t / v.T) } });

const Laws = {
  q: '', cat: -1,
  render() {
    const v = $('#view-laws');
    v.innerHTML = `<div class="wrap"><div class="sec-title" style="margin-top:0"><h3>مكتبة القوانين</h3><p>${LAWS.length} قانوناً مع حاسبة فورية</p></div>
    <div class="cat-tools"><input class="search" id="lawQ" placeholder="ابحث عن قانون… (كيرشوف، رنين، بلانك)"><div class="chips">${[{ id: -1, name: 'الكل' }, ...LAWCATS].map(c => `<button class="chip ${this.cat === c.id ? 'on' : ''}" data-c="${c.id}">${c.id === -1 ? 'الكل' : c.id === 0 ? 'أساسية' : 'ف' + c.id}</button>`).join('')}</div></div><div id="lawBody"></div></div>`;
    $('#lawQ').value = this.q; $('#lawQ').oninput = e => { this.q = e.target.value; this.body(); };
    $$('.chip', v).forEach(b => b.onclick = () => { this.cat = +b.dataset.c; this.render(); });
    this.body();
  },
  body() {
    const q = this.q.trim();
    const html = LAWCATS.filter(c => this.cat === -1 || c.id === this.cat).map(c => {
      const list = LAWS.filter(l => l.cat === c.id && (!q || (l.name + (l.sym || '')).includes(q))); if (!list.length) return '';
      const col = c.id ? chById(c.id).c : 'var(--accent)';
      return `<div class="cat-ch" style="--c:${col}"><span class="dot"></span><h3>${c.name}</h3></div><div class="laws-grid">${list.map(l => `<div class="law-card"><h4>${l.name}</h4><div class="fx">${l.fx}</div>${l.sym ? `<div class="sym">${l.sym}</div>` : ''}${l.calc ? `<details class="calc-d"><summary>حاسبة</summary><div class="calc" data-l="${l.id}">${l.calc.in.map(i => `<div><label>${i[1]} ${i[2] ? '(' + i[2] + ')' : ''}</label><input class="num" type="number" step="any" data-k="${i[0]}" value="${i[3]}"></div>`).join('')}<div class="res"></div></div></details>` : ''}</div>`).join('')}</div>`;
    }).join('');
    $('#lawBody').innerHTML = html || '<div class="empty">لا نتائج</div>';
    $$('.calc').forEach(box => { const l = lawById(box.dataset.l); const upd = () => { const v = {}; $$('input', box).forEach(i => v[i.dataset.k] = +i.value); let r = l.calc.f(v); $('.res', box).textContent = `${l.calc.out} = ${isFinite(r) ? fmtNum(r) : '—'} ${l.calc.u}`; }; $$('input', box).forEach(i => i.oninput = upd); upd(); });
  }
};
