const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1440, height: 900 } }); const pg = await ctx.newPage();
  pg.on('pageerror', e => console.log('ERR', e.message));
  await pg.goto('file://' + __dirname + '/out.html'); await pg.waitForTimeout(1200); await pg.screenshot({ path: 'shots/f_splash.png' });
  await pg.click('.splash button'); await pg.waitForTimeout(600);
  await pg.evaluate(() => location.hash = 'exp/neon'); await pg.waitForTimeout(800); await pg.screenshot({ path: 'shots/f_pred.png' });
  await pg.click('.pred-o button[data-i="1"]'); await pg.waitForTimeout(200); await pg.click('[data-r="1"]'); await pg.waitForTimeout(200);
  await pg.click('#fGuide'); await pg.waitForTimeout(300); await pg.click('#guideBar [data-a="next"]'); await pg.waitForTimeout(300);
  await pg.click('#ctls .btnrow button:nth-child(1)'); await pg.waitForTimeout(3500); console.log('guide step', await pg.evaluate(() => Features.g && Features.g.i));
  await pg.click('#ctls .btnrow button:nth-child(2)'); await pg.waitForTimeout(2500); console.log('guide step', await pg.evaluate(() => Features.g && Features.g.i)); await pg.screenshot({ path: 'shots/f_guide.png' });
  await pg.click('.pred-modal [data-r="2"]'); await pg.waitForTimeout(300); await pg.screenshot({ path: 'shots/f_reveal.png' });
  await pg.evaluate(() => location.hash = 'exp/xl_f'); await pg.waitForTimeout(600); await pg.evaluate(() => $$('.pred-modal').forEach(x => x.remove()));
  await pg.waitForTimeout(2500); await pg.click('#recBtn'); await pg.evaluate(() => { const i = document.querySelector('#ctls .ctl input'); i.value = 150; i.oninput(); }); await pg.waitForTimeout(2500); await pg.click('#recBtn');
  await pg.click('#fSnap'); await pg.evaluate(() => { const i = document.querySelector('#ctls .ctl input'); i.value = 300; i.oninput(); }); await pg.waitForTimeout(2500); await pg.click('#recBtn');
  await pg.click('#fProbe'); await pg.waitForTimeout(200);
  const box = await pg.evaluate(() => { const st = Runner.stage; const n = st.C.nodes; const r = st.cv.getBoundingClientRect(); const pt = i => [r.left + n[i].x * st.cam.z + st.cam.x, r.top + n[i].y * st.cam.z + st.cam.y]; const c = st.C.get('L'); return [pt(c.n1), pt(c.n2)]; });
  await pg.mouse.click(...box[0]); await pg.mouse.click(...box[1]); await pg.waitForTimeout(800); await pg.screenshot({ path: 'shots/f_snap_probe.png' });
  console.log(await pg.evaluate(() => document.querySelector('#fitTxt').innerText));
  await pg.click('#fPres'); await pg.click('#fPen'); await pg.mouse.move(600, 400); await pg.mouse.down(); await pg.mouse.move(700, 450, { steps: 5 }); await pg.mouse.up(); await pg.waitForTimeout(300); await pg.screenshot({ path: 'shots/f_present.png' }); await pg.click('#fPres');
  const [pop] = await Promise.all([ctx.waitForEvent('page'), pg.click('#fSheet')]); await pop.waitForTimeout(800); await pop.screenshot({ path: 'shots/f_sheet.png', fullPage: true }); await pop.close();
  await pg.click('#fShare'); await pg.waitForTimeout(300); console.log('link', await pg.evaluate(() => { const i = document.querySelector('.pred-modal input'); return i && i.value; }));
  await pg.evaluate(() => location.hash = 'examples'); await pg.waitForTimeout(600); await pg.click('[data-step="0"]'); await pg.click('[data-step="0"]'); await pg.screenshot({ path: 'shots/f_examples.png' });
  await pg.click('[data-exp="10"]'); await pg.waitForTimeout(3000); console.log('ex5', await pg.evaluate(() => document.querySelector('#reads').innerText.replace(/\n/g, ' | ').slice(0, 200)));
  await pg.evaluate(() => location.hash = 'examples'); await pg.waitForTimeout(500); await pg.click('[data-lab="0"]'); await pg.waitForTimeout(2000); await pg.screenshot({ path: 'shots/f_exlab.png' });
  await pg.evaluate(() => location.hash = 'maps/3'); await pg.waitForTimeout(600); await pg.screenshot({ path: 'shots/f_map.png' });
  await pg.evaluate(() => { location.hash = 'lab'; }); await pg.waitForTimeout(800); await pg.evaluate(() => { const C = FreeLab.C; C.clear(); C.add('battery', 2, 4, 2, 10, { val: 24 }); C.add('bulb', 2, 4, 8, 4, { val: 20, rated: 3 }); C.add('wire', 8, 4, 8, 10); C.add('wire', 8, 10, 2, 10); C.resetState(); FreeLab.stage.fit(); }); await pg.waitForTimeout(1500); await pg.screenshot({ path: 'shots/f_burn.png' });
  console.log('burnt', await pg.evaluate(() => FreeLab.C.comps.some(c => c.burnt)));
  await b.close();
})();
